// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmPB__V_TfmNriumPDisDi5eNQyHWhrXw',
    appId: '1:15089311660:web:4121f326ea08eb6a396409',
    messagingSenderId: '15089311660',
    projectId: 'pistache-40b12',
    authDomain: 'pistache-40b12.firebaseapp.com',
    storageBucket: 'pistache-40b12.appspot.com',
    measurementId: 'G-DZN846PE1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjjxic0l__4GdvRI9L1G0GZIeOD5JRoPQ',
    appId: '1:15089311660:android:5d33434af85e8378396409',
    messagingSenderId: '15089311660',
    projectId: 'pistache-40b12',
    storageBucket: 'pistache-40b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRvQBsKu3SoXOSpOTfZqg4Ob8zzBw0Cs',
    appId: '1:15089311660:ios:0e2c34793bd0ac32396409',
    messagingSenderId: '15089311660',
    projectId: 'pistache-40b12',
    storageBucket: 'pistache-40b12.appspot.com',
    iosBundleId: 'dev.thiagofontes.pistache',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQRvQBsKu3SoXOSpOTfZqg4Ob8zzBw0Cs',
    appId: '1:15089311660:ios:814d13068d867cb9396409',
    messagingSenderId: '15089311660',
    projectId: 'pistache-40b12',
    storageBucket: 'pistache-40b12.appspot.com',
    iosBundleId: 'dev.thiagofontes.pistache.RunnerTests',
  );
}
